# Generated by Django 3.2 on 2021-05-07 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_example'),
    ]

    operations = [
        migrations.DeleteModel(
            name='example',
        ),
    ]
